# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxi8rDCjg5pYnR0vnm7ahP_ZB9KWY3Yb
"""

!pip install git+https://github.com/openai/whisper.git
!pip install ffmpeg-python

import ffmpeg

input_file = "/content/Scam_Call.mp3"
output_file = "/content/converted.wav"

ffmpeg.input(input_file).output(output_file).run(overwrite_output=True)
print("✅ Conversion done: MP3 → WAV")

import whisper

# Load the Whisper model
model = whisper.load_model("base")  # You can also try "small", "medium", or "large"

# Transcribe the WAV audio
result = model.transcribe(output_file)

# Show transcription
print("🎙️ Transcription:")
print(result["text"])

# Define common spam keywords
spam_keywords = [
    "otp", "one time password", "urgent", "verify", "bank", "press 1",
    "account locked", "security", "fraud", "final warning", "suspicious activity"
]

# Simple function to check for spam
def is_spam_call(transcript, keywords):
    transcript = transcript.lower()
    for word in keywords:
        if word in transcript:
            return True, word
    return False, None

# Run the detector
is_spam, keyword = is_spam_call(result["text"], spam_keywords)

# Print result
if is_spam:
    print(f"⚠️ Spam Detected! Keyword matched: '{keyword}'")
else:
    print("✅ This call seems safe.")